### PR TITLE
[WIP] Add deployment config controller generation.

### PR DESCRIPTION
**Pull request by cdrage**
This adds deployment config controller generation to Kedge.

### CODE REVIEW

**Comment by cdrage** [comment]
WIP!!

Doing this to reflect some current changes going underway and to show @containscafeine my work too since he's doing something very similar with jobs (same sort of implementation with fix, unmarshal, transform, etc. methods)

TODO:
 - Get this to actually work
 - Add `openshift.go` file that will convert the default (deployment) to deploymentconfig
 - tests

**Comment by cdrage** [comment]
This also depends on: https://github.com/kedgeproject/kedge/pull/250 which is yet to be merged.

**Comment by kadel** [comment]
related to #237

**Comment by surajssd** [comment]
@cdrage can you rebase this one so that I can give you first round of my review ?

**Comment by cdrage** [comment]
@surajssd I'm going to close this for now as it's far from ready and a lot WIP. Got blocked on openshift-go library support.

**Pull request closed without merging**
