### PR TITLE
Update vendor logrus

### PR DESCRIPTION
**Pull request by surajssd**
logrus has moved from `github.com/Sirupsen/logrus` to `github.com/sirupsen/logrus` so updating all the imports and also vendoring the new version!

### CODE REVIEW

**Comment by surajssd** [comment]
This is blocker for #295

**Comment by surajssd** [comment]
Thanks @containscafeine

**Comment by kadel** [comment]
hmm, this might cause problems :-(

OpenShift uses older logrus (and it is importing from path with capital 'S')

This newer version might collide with a version that is required by OpenShift.

**Comment by surajssd** [comment]
@kadel do I move back to older version ?

**Comment by surajssd** [comment]
@kadel this https://github.com/kedgeproject/kedge/pull/302 will solve the issue! Need your review on it!

**Pull request merged**
