### PR TITLE
Redesign site + adds logo

### PR DESCRIPTION
**Pull request by cdrage**
Adds a new front-page as well as a new logo licensed by CC0.

### CODE REVIEW

**Comment by cdrage** [comment]
*A lot* to take in a lot happening here. 

Essentially, a massive redesign of the website as well as the introduction of a new (licensed by CC0) logo.

In order to test this out / preview it:

1. Install Jekyll
2. Pull down this branch
3. `jekyll serve .`

Otherwise, you can find a preview of the new front-end / logo:
frontend

**Comment by cdrage** [comment]
ping @kadel @surajnarwade @surajssd @pradeepto

**Comment by pradeepto** [comment]
Comments as per discussion on chat.

**Comment by cdrage** [comment]
Going to merge this in as-is so we can have a live-preview and have people comment on it / make PR's for any changes.

**Comment by kadel** [comment]
It would be nice, to sum up what you have talked about or better paste chatlog or at least say where the chat took place :-( 
I wasn't able to find it :-(

**Pull request merged**
