### PR TITLE
Fix the multiple CI issues with regards to using Wordpress

### PR DESCRIPTION
**Pull request by cdrage**
Instead of using the standard Wordpress containers, I have switched to
using a combination of Guestbook as well as Redis Master + Slaves.

Ensuring that we don't run out of memory (common issue on the CI's) as
well as creating a faster testing suite.

### CODE REVIEW

**Comment by cdrage** [comment]
Added WIP.

Things to do:

- [ ] Convert all tests (currently converting each one manually and testing them)

**Comment by cdrage** [comment]
Ready for review @surajnarwade @kadel @containscafeine

**Comment by kadel** [comment]
This looks good, but I'm not sure about removing all the readme.md s.

They contain information that we don't have anywhere else. I would keep them.

**Comment by cdrage** [comment]
@kadel They're not exactly consistent (some of the examples are missing the readme and some other readme's are not as good / detailed as others).

I'll edit the PR and add the README's then ping you again :+1:

**Comment by kadel** [comment]
> @kadel They're not exactly consistent (some of the examples are missing the readme and some other readme's are not as good / detailed as others).

I know :-( , but some of them have useful information I don't want lose it

**Comment by cdrage** [comment]
Hey @kadel I've gone ahead and re-added the `README.md` as well as modified it so it reflects the new tests (guestbook) rather than using wordpress.

**Comment by kadel** [comment]
Think you @cdrage. Great work!!  :tada: 

LGTM

**Comment by cdrage** [comment]
Alright, let's get this show on the road. Going to merge this in so that master (finally) passes :+1: 

On a side note, tests pass in 2 minutes rather than 40 :100: :100: :100:

**Pull request merged**
