### PR TITLE
Updated shortcuts for ingress and route

### PR DESCRIPTION
**Pull request by surajnarwade**
Updated shortcuts for ingress and routes so that it should reflect in JSON schema
and then it will help PR #592

### CODE REVIEW

**Comment by surajnarwade** [comment]
@cdrage @kadel @containscafeine , we have to merge this irrespective of status of CI, because after this PR gets merged JSON schema will be updated and tests #592 will be passed

**Comment by cdrage** [comment]
@surajnarwade You have my go ahead :) Ideally we'd get both this and #592 merged at the same time.

**Comment by surajnarwade** [comment]
@kadel @containscafeine one more +1 needed

**Comment by kadel** [comment]
+1
BTW: I would consider switching to 1 LGTM system ;-) What do you think?

**Comment by surajnarwade** [comment]
@pradeepto are you okay with  1 LGTM system ?

**Comment by cdrage** [comment]
1 LGTM system = LGTM to me :+1:

**Comment by pradeepto** [comment]
> @pradeepto are you okay with 1 LGTM system ?

You folks are the maintainers. You are the ones who will decide this.

**Comment by surajnarwade** [comment]
Let's merge this :)

**Pull request merged**
