### PR TITLE
Remove verbose output e2e tests

### PR DESCRIPTION
**Pull request by cdrage**
Removes the verbose output of e2e tests and slightly changes the output
y adding an echo of using `kubectl get po --all-namespaces -w`.

### CODE REVIEW

**Comment by ashetty1** [comment]
@cdrage I think another way to do this would be to add `run_e2e.sh -v' option to the script itself. WDYT?

Cc: @surajssd @kadel

**Comment by cdrage** [comment]
@ashetty1 you mean `make test-e2e -v` ?

**Comment by ashetty1** [comment]
@cdrage Yes. `make VERBOSE=yes / no`

**Comment by cdrage** [comment]
Updated with your suggested changes @ashetty1 let me know if these are good.

**Pull request merged**
