### PR TITLE
Adding feature of taking input from URL

### PR DESCRIPTION
**Pull request by surajnarwade**
inspired from https://github.com/redhat-developer/opencompose/commit/dc6442780f0ba9a190c61d545bcc2c65fe2ae430

### CODE REVIEW

**Comment by kadel** [comment]
Haven't checked the code of this yet. But this might be a bit trickier than in OpenCompose.

First is that It has to be possible to specify multiple urls.

Second is how `extraResource` are handled.

**Comment by surajnarwade** [comment]
@kadel , currently this PR supports multiple urls as well but for second thing(`extraResources`), we need to error out as this is not doable

**Comment by surajssd** [comment]
I think we need to hold on for this feature, until there is utmost requirement and lot of user request to add it.

**Comment by surajssd** [comment]
Also because it is adding lot of complications to the existing features.

**Comment by kadel** [comment]
I agreed with @surajssd, I also think that this feature is not that important, and currently, it might add more complications that benefits.

Let's wait with this.  We have a lot of other issues that we need to solve that are more pressing than this.

**Comment by pradeepto** [comment]
This is an eyesore. @surajnarwade I discussed this with @surajssd and closing it for now. We will come back to it when we have to.

**Pull request closed without merging**
