### PR TITLE
Update README within examples

### PR DESCRIPTION
**Pull request by cdrage**
This makes the examples simpler by making them one file as well as
updating the README's to a full description of how to use said example.

### CODE REVIEW

**Comment by cdrage** [comment]
Seems *a lot* simpler. Thoughts @kadel @pradeepto ?

**Comment by containscafeine** [comment]
@cdrage we support both because this feature was requested, but we don't encourage using it, and hence follow the best practices in our examples. Refer to discussion on #17.

**Comment by cdrage** [comment]
@containscafeine ah darn, I'll split them back up to multiple files then.

**Comment by cdrage** [comment]
@containscafeine @surajssd gone ahead and updated the PR with multiple-files rather than a single kedge file.

**Comment by surajssd** [comment]
before merge @cdrage can you update the commit to be according to changes we have made now ?

**Comment by cdrage** [comment]
@surajssd done

**Pull request merged**
