### PR TITLE
Improved help on error on kedge commands

### PR DESCRIPTION
**Pull request by surajnarwade**
For example,
```
kedge apply
No files were passed. Please pass file(s) using '-f' or '--files'
See 'kedge apply -h' for help and examples.
```

Similar to `kubectl`

### CODE REVIEW

**Comment by surajnarwade** [comment]
@containscafeine @cdrage @kadel does this make sense ?

**Comment by cdrage** [comment]
@surajnarwade Why not use logrus?

**Comment by surajnarwade** [comment]
@cdrage , I didn't get it, logrus where ?

**Comment by surajnarwade** [comment]
@cdrage Kubernetes also uses same logic for this help

**Review by concaf — COMMENTED** [review]
I like this approach. +1 from me once tests are fixed

**Pull request closed without merging**
