### PR TITLE
Add jsonschmea generation to travis

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by surajssd** [comment]
@kadel on travis where can I add the @kedge-schema-bot 's ssh private key, so that this script will work for sure!

**Comment by kadel** [comment]
> @kadel on travis where can I add the @kedge-schema-bot 's ssh private key, so that this script will work for sure!

on travis? You don't have to do that. You just have to give write permissions to @kedge-schema-bot  to this repo

**Comment by kadel** [comment]
btw: I just found out that there already is @kedge-bot. It would be much better if we use the same user for this

**Comment by kadel** [comment]
I think that @kedge-bot  was created by @cdrage

**Comment by kadel** [comment]
Shouldn't this run only on master?
Right now it runs on all branches/forks.

**Comment by kadel** [comment]
Any progress on this?

**Comment by surajssd** [comment]
We will revisit this later, right now we won't be doing complete automation of schema generation when we get to that stage we will do this also!

**Pull request closed without merging**
