### PR TITLE
Adds an undeploy command

### PR DESCRIPTION
**Pull request by cdrage**
Refactors the `pkg/cmd/deploy.go` file for adding an undeploy command.

### CODE REVIEW

**Comment by pradeepto** [comment]
Good stuff @cdrage. How does it work when there are more than one services defined in a single file? All the resources are deleted?

**Comment by cdrage** [comment]
@pradeepto Yes. There is a for loop that iterates through all files that were generated and deletes them from the cluster.

**Comment by surajssd** [comment]
I have no comments about the approach used here, but this is cool and consice so LGTM

**Comment by pradeepto** [comment]
> @pradeepto Yes. There is a for loop that iterates through all files that were generated and deletes them from the cluster.

Ah! I missed the collapsed bit of the code which had the loop. LGTM.

**Comment by pradeepto** [comment]
Just realised that we need documentation for `undeploy` either as a part of this PR or the user-guide PR. Also, we should clearly mention in the readme, user-guide and also as a part of the CLI help that this command will delete the resource or resources and it is a permanent operation. That makes me wonder ...

Questions:
1.  Do we need a better name for `deploy` and `undeploy`?  ( other day, @kadel suggested `create` and `delete` since they are k8s terms)
2.  Whatever name we choose, should we have a confirmation step before a permanent destructive operation? e.g. "This operation will delete your resources. Are you sure?"

cc @cdrage @surajssd @kadel @containscafeine @surajnarwade Please pitch in. Both these questions are UX related.

**Comment by kadel** [comment]
> Whatever name we choose, should we have a confirmation step before a permanent destructive operation? e.g. "This operation will delete your resources. Are you sure?"

I think that if we use `create`/`delete` that we don't need confirmation. 'delete' should be clear for every user that this is going to be destructive operation.

**Comment by cdrage** [comment]
@kadel @pradeepto 
IMO create/delete > deploy/undeploy as it will follow similar `kubectl` constructs so it'd be super easy for people to pick up.

**Comment by kadel** [comment]
@cdrage so you are on board with changing it to create/delete? 

Then let's merge this PR as it is. We will rename both commands together in separate PR

**Comment by cdrage** [comment]
@kadel Yeah, I agree changing to create / delete.

**Pull request merged**
