### PR TITLE
Add Gitea + make improvements to examples

### PR DESCRIPTION
**Pull request by cdrage**
Adds Gitea to the examples as well as changes the README of Wordpress
and GitLab to match the other examples.

.yml is also changed to .yaml

### CODE REVIEW

**Comment by cdrage** [comment]
Any ideas why I'm getting these errors? Another thing too, it doesn't look like there is actually any output to the error, but if I run it manually, I can see it:

Example:
```
github.com/kedgeproject/kedge  add-gitea ✔                                                                                                                                     24m  ⍉
▶ ./kedge generate -f examples/gitea/gitea.yaml
2018/02/28 13:12:54 The kedgefile is not valid. see errors :
livenessProbe: Additional property livenessProbe is not allowed
readinessProbe: Additional property readinessProbe is not allowed
postgresql-user: Additional property postgresql-user is not allowed
secrets.0.data: Invalid type. Expected: object, given: null
```

Travis CI errors:

```
--- FAIL: Test_examples (6.56s)
	cmd_test.go:158: kedge generate failed for - /home/travis/gopath/src/github.com/kedgeproject/kedge/examples/gitea/gitea.yaml
		 Error is - 
=== RUN   Test_init
```

Ping @surajnarwade

**Comment by cdrage** [comment]
@surajnarwade @kadel @containscafeine Mind testing this?

**Comment by surajnarwade** [comment]
@cdrage , I am not able to run `gitea` app on minikube,

```
 $ kubectl get all
NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/gitea        1         1         1            0           2m
deploy/postgresql   1         1         1            0           2m

NAME                       DESIRED   CURRENT   READY     AGE
rs/gitea-7c6b556456        1         1         0         2m
rs/postgresql-66cf8d5c86   1         1         0         2m

NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/gitea        1         1         1            0           2m
deploy/postgresql   1         1         1            0           2m

NAME                       DESIRED   CURRENT   READY     AGE
rs/gitea-7c6b556456        1         1         0         2m
rs/postgresql-66cf8d5c86   1         1         0         2m

NAME                             READY     STATUS                       RESTARTS   AGE
po/gitea-7c6b556456-cb5bv        0/1       Running                      0          2m
po/postgresql-66cf8d5c86-8d4jz   0/1       CreateContainerConfigError   0          2m

NAME             TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                     AGE
svc/gitea        LoadBalancer   10.98.145.146   <pending>     80:30643/TCP,22:30583/TCP   2m
svc/kubernetes   ClusterIP      10.96.0.1       <none>        443/TCP                     5m
svc/postgresql   ClusterIP      10.109.51.20    <none>        5432/TCP                    2m
```

**Comment by cdrage** [comment]
@surajnarwade works for me, can you post the logs from `kubectl describe po/postgresql-66cf8d5c86-8d4jz`

**Pull request closed without merging**
