### PR TITLE
Fix guestbook-demo to work on openshift

### PR DESCRIPTION
**Pull request by kadel**
related to #483

### CODE REVIEW

**Comment by surajssd** [comment]
```console
$ kedge create -f .
W1124 08:13:22.956505   31972 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
service "backend" created
W1124 08:13:24.214638   31981 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
deployment "backend" created
W1124 08:13:24.464889   32000 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
persistentvolumeclaim "mongodb-data" created
W1124 08:13:24.986851   32008 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
service "mongodb" created
W1124 08:13:26.284518   32025 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
secret "mongodb-admin" created
W1124 08:13:26.723313   32047 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
secret "mongodb-user" created
W1124 08:13:28.016186   32057 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
configmap "mongodb-user" created
W1124 08:13:28.569403   32085 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
deployment "mongodb" created
W1124 08:13:29.125537   32095 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
service "frontend" created
W1124 08:13:31.518919   32121 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger
deployment "frontend" created
```

mongodb pod in `CrashLoopBackOff`

```console
$ oc get pods
NAME                       READY     STATUS             RESTARTS   AGE
backend-1706566060-wqj6w   1/1       Running            2          8m
frontend-855248943-rdm2z   1/1       Running            0          8m
mongodb-1672985142-1cl96   0/1       CrashLoopBackOff   4          8m
```


Mongo logs

```console
$ oc logs mongodb-1672985142-1cl96 -f
note: noprealloc may hurt performance in many applications
=>  Waiting for MongoDB daemon up
Fri Nov 24 02:47:47.375 [initandlisten] MongoDB starting : pid=14 port=27017 dbpath=/var/lib/mongodb/data 64-bit host=mongodb-1672985142-1cl96
Fri Nov 24 02:47:47.375 [initandlisten] db version v2.4.9
Fri Nov 24 02:47:47.375 [initandlisten] git version: nogitversion
Fri Nov 24 02:47:47.375 [initandlisten] build info: Linux c1bg.rdu2.centos.org 2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64 BOOST_LIB_VERSION=1_53
Fri Nov 24 02:47:47.375 [initandlisten] allocator: tcmalloc
Fri Nov 24 02:47:47.375 [initandlisten] options: { config: "/etc/mongod.conf", dbpath: "/var/lib/mongodb/data", nohttpinterface: "true", noprealloc: "true", oplogSize: 64, port: 27017, quiet: "true", setParameter: [ "textSearchEnabled=false" ], smallfiles: "true" }
Fri Nov 24 02:47:47.376 [initandlisten] exception in initAndListen std::exception: boost::filesystem::status: Permission denied: "/var/lib/mongodb/data/mongod.lock", terminating
Fri Nov 24 02:47:47.376 dbexit: 
Fri Nov 24 02:47:47.376 [initandlisten] shutdown: going to close listening sockets...
Fri Nov 24 02:47:47.376 [initandlisten] shutdown: going to flush diaglog...
Fri Nov 24 02:47:47.376 [initandlisten] shutdown: going to close sockets...
Fri Nov 24 02:47:47.385 [initandlisten] shutdown: waiting for fs preallocator...
Fri Nov 24 02:47:47.385 [initandlisten] shutdown: lock for final commit...
Fri Nov 24 02:47:47.385 [initandlisten] shutdown: final commit...
Fri Nov 24 02:47:47.385 [initandlisten] shutdown: closing all files...
Fri Nov 24 02:47:47.385 [initandlisten] closeAllFiles() finished
Fri Nov 24 02:47:47.385 dbexit: really exiting now
=>  Waiting for MongoDB daemon up
=>  Waiting for MongoDB daemon up
...
=>  Waiting for MongoDB daemon up
=> Giving up: MongoDB daemon is not up!
```

It failed as `[initandlisten] exception in initAndListen std::exception: boost::filesystem::status: Permission denied: "/var/lib/mongodb/data/mongod.lock", terminating`

**Comment by kadel** [comment]
```W1124 08:13:22.956505   31972 factory_object_mapping.go:423] Failed to download OpenAPI (unknown), falling back to swagger```

This is just warning showing because `kubectl` is used against OpenShift. It is just warning, no error.



MongDB error
```
It failed as [initandlisten] exception in initAndListen std::exception: boost::filesystem::status: Permission denied: "/var/lib/mongodb/data/mongod.lock", terminating
```

Looks more like an issue with PV on your cluster setup? Are you using Minishift?

**Comment by surajssd** [comment]
@kadel yes I tried that on minishift which has no addons enabled!

**Comment by kadel** [comment]
can't reproduce it :-( 
I've tried that on two different minishift versions and on `oc cluster up` and it worked for me every time

**Comment by cdrage** [comment]
LGTM.

(side-bit, we need to get these README's tutorials and such on the site. but that's for later #501 )

**Pull request merged**
