### PR TITLE
Fixed `kedge init` according to new syntax

### LINKED ISSUE #587: outdated `kedge init`
Since our kedge structure is updated. We need to update `kedge init` as well

### PR DESCRIPTION
**Pull request by surajnarwade**
Fixes #587

### CODE REVIEW

**Comment by ashetty1** [comment]
@surajnarwade those semaphore errors are because of tests timing out.

**Comment by cdrage** [comment]
Tests?

**Comment by surajnarwade** [comment]
@cdrage , tests added

**Comment by surajnarwade** [comment]
@kadel @cdrage @containscafeine review please

**Comment by surajnarwade** [comment]
@cdrage @containscafeine one more review and ...

**Comment by cdrage** [comment]
LGTM

**Pull request merged**
