### PR TITLE
feat(kedge build): using s2i to do image builds

### PR DESCRIPTION
**Pull request by surajssd**
Now you can do builds using openshift s2i

### CODE REVIEW

**Comment by surajssd** [comment]
Usage: 

```
kedge build --s2i -i docker.io/surajd/surajpythonimage
```

I have created this repo to try this feature: https://github.com/surajssd/localbuild

**Review by kadel — CHANGES_REQUESTED** [review]
This is not using S2I, it just creates BuildConfig with Dockerfile :-(

**Comment by kadel** [comment]
This is not what #309 was supposed to be about.

This is also useful but it is not using s2i. It can be used only on OpenShift clusters where building from Dockerfile is allowed (currently this is a security risk)

I don't think that doing git autodetection is wise. It has a lot of problems as we saw in Kopose.
It would rather do builds with binary source strategy
```
...
  source: 
    type: "binary"
...
```
and use `oc start-build` to stream local directory to openshift buildconfig.

**Comment by surajssd** [comment]
It is hard for a developer to know the builder image, so not sure about the flag where user provides the builder image.


> I don't think that doing git autodetection is wise. It has a lot of problems as we saw in Kopose. It would rather do builds with binary source strategy

What do you mean by git autodetection? I think what is done right now in the code is similar to what openshift/oc does.


> use oc start-build to stream local directory to openshift buildconfig.

We can even be alias to the `oc new-build ...` and `oc start-build ...`, we don't even need to create the configs. For the repo: https://github.com/surajssd/localbuild I can run following commands to get the code being built using s2i source strategy:

```
oc new-build .
oc start-build localbuild --from-dir .
```

**Comment by kadel** [comment]
> It is hard for a developer to know the builder image, so not sure about the flag where user provides the builder image.

but this is what s2i is about ;-), `oc new-build` can detect basic builder images, but we still need an option for using a custom one.

What you currently have in this PR is not S2I but plain `docker build`. 

> What do you mean by git autodetection? I think what is done right now in the code is similar to what openshift/oc does.

The part where it detects git remote from the directory. What if the directory is not in git? What if i have local changes not committed to git that I want to build for test? What if git remote is not accessible from OpenShift cluster? 

I think that should let user specify git url rather than autodetecting it. It will be clear for user that build is happening from git remote and not from local directory.

The current way is really confusing, especially when user have local changes that he wants build. Also, typical github setup is that  developer has repository cloned via ssh and CI/CD can't clone it using ssh, it should use https.

> We can even be alias to the oc new-build ... and oc start-build ..., we don't even need to create the configs. For the repo: https://github.com/surajssd/localbuild I can run following commands to get the code being built using s2i source strategy:


if we can specify everything that we need using `oc new-build` then why not.

**Comment by surajssd** [comment]
Okay now I am confused, should we be just alias the `oc build ...` or keep creating the configs?

**Comment by kadel** [comment]
If `oc new-build` saves us work and does everything that we need what we can use it.

Let's go back to #309 and do some research and document what we actually want to accomplish before jumping to implementation.

**Pull request closed without merging**
