### PR TITLE
Adding tests for jobs

### PR DESCRIPTION
**Pull request by ashetty1**
Issue #270

### CODE REVIEW

**Comment by containscafeine** [comment]
@ashetty1 I think semaphoreci fails for some another reason, can you do a force push again? Maybe rebase or make some changes in the comments.

**Comment by kadel** [comment]
@containscafeine @ashetty1 You should be able to just restart the job.

**Comment by kadel** [comment]
I've just triggered a rebuild.

**Comment by ashetty1** [comment]
@containscafeine @kadel  from the logs, it seems like the semaphore tests are taking a long time to run, and therefore failing.

**Comment by cdrage** [comment]
Looks to be a false positive for CI passing. The script isn't giving a correct error-out code (exit code 1), @surajssd are you able to check it out? https://semaphoreci.com/cdrage/kedge/branches/pull-request-297/builds/6

**Comment by surajssd** [comment]
@cdrage yeah false positives, one test failed, but the script still says that test has passed!

**Comment by surajssd** [comment]
ping @ashetty1

**Comment by cdrage** [comment]
Hey @ashetty1 could you rebase to master and push to trigger a new build?

**Comment by cdrage** [comment]
Hey @ashetty1 you need to update your commit message, it is blank. Add a descriptive message.

**Comment by surajssd** [comment]
I think the commit message is added and the PR is ready to merge!

**Pull request merged**
