### PR TITLE
Remove tests

### PR DESCRIPTION
**Pull request by cdrage**
I don't see anywhere in the code where these tests are being used.

Let's re-introduce these when we add cmd/cli tests.

### CODE REVIEW

**Comment by containscafeine** [comment]
Lol, I love the title of this PR :rofl:

**Comment by surajssd** [comment]
Let's not remove those tests rather create an issue saying that we need to add `cmd line` tests!

**Comment by cdrage** [comment]
@surajssd Okay, mind opening the issue and closing this PR?

**Comment by surajssd** [comment]
closing this in favour of https://github.com/kedgeproject/kedge/issues/58

**Pull request closed without merging**
